deploy:
  provider: pypi
  username: __token__
  password:
    secure: MPNixzFcRmAuOh5gXS1CXFdDR/c6MVN9FxzVt/4yfyggGgfXfuz17LZio+cR19QX3HdPofnxBm38uBUKsYSps8LFt7TglnsYFUZXEnTnJ96ImFRuzKC11sYqZJV5crunwSB7DrXAzejIlqulK6/wkLq9otMZFEUR1B3BBbzdl78K9PVa0fgQzs7qWngB7mTVdXVkRDohsqrUfIFoRtW0ou7b9ho/ck8fiHM+Pa9Pwb+p9vTnEZzh60+vU2Et2fM+b5ffHxOeFypsqP93VrdgnkEpE/pK5B+ipXVo6a0JvF6hvww/V4q2Vp8ujkgGVNE2o49KKM27DqbzBzSHQlV7I+LZz/NVo4sF3iX2zir1Q2F2+jkPDrTew9D4cQbHKD6QJPD2Cb2kHOlzfkDgXtsmEOY1ldT7jrIfzRKofHJ0tWSjJIoxiu/WUA2y3laKHkmqYhVCRWkY31v0MZbbs8GG6qxNm4UhD3IZRtaSb54clkRnYV63K9dkj/FBbCIUEPzlwUYPAdNso3D9E10WqBiqTaugXPfuJJaJa8PGm1np2FjBPZtJNnPrxv5Kskk6z5Yfw+AY3QiTLoQlymNAm7VOX54DMhbDtgtiwYTdW6oos9mKSMmG+Z+LhWbQSbO+4Jj1CGXRtcfv2Z/eMg0nP3VUtHScLdrb0qj4ZYbpj9lBfpw=
  on:
    branch: main
