language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: 0gGR1DtaIVusoLLCZBmLPC2cqXSeL7YRIMwa+1dtCfS0uLR8lerq7Fjg3LlJIwcnOa/iA+fJXfhE/jccJKx0Oj5VJIplu+0VH3lU/T5gFC2v4UeMdFpzs6Io3KujaXMWC8rBlWxwSqPR8uT4Y1Qml/yTvIwLsskETyZS4GuG21OG+63FlxvePkagWjx5ypNdpzZh+OC1zB0nGKCYr2IB+MNoojme/afMWv2zSJb4pFyAONKpnZxleV07V2oD4IBqLRRAcb7cI63uIorV1r5Ym1DkZ+dBrdfErfEvEvWwatNHKR4D+lSTold47qBbG3v1O/vAwRXY4aicEVHH3DI9fF2RNbq2PqThyaZeQXIgOnkUXCuKquU4ril8DsP6h27FQYJ9Lb36m9kx1g7E+R0g524nKmbAZ2hoDUzsjiz6qg0jL4hC3XBpeGf/LytrziatM3EIs6Qifs9nJeVHtAineMR3XowG0ZHvxadzHOulM1vthdvHMcz8s88KsrJhVv23WvVERgkL2ipdZhTLjLdTxdSXg5nmZZxye78c4AnKxGtBOAxA9YBMVkjmKEv3PCM4jOr5Gb4JzWo48gKgAWEW6jkVBm/kA3N8CU9m9OYFgG5006kgszlzsHewz0j+hDGp8I28XLekO7LMZDO3BtxoQNeGs0eGHDSlVMAXC7Y7eK4=
  on:
    branch: main
